PControlInv/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as cViews
from stockList import views as sViews
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('stockList/', include(('stockList.urls', 'stockList'), namespace='stockList')),
    path('admin/', admin.site.urls),
    path('', login_required(cViews.index), name='index'),
    path('register/', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tables/', login_required(sViews.tables), name='tables'),
    path('adding_stock/', login_required(sViews.add_stock), name='stockAdd'),
    path('reporte_excel/', login_required(sViews.ReporteExcel.as_view()), name='reporte_excel'),
    path('update_stock/<str:pk>/', login_required(sViews.update_stock), name="update_stock"),
    path('delete_stock/<str:pk>/', login_required(sViews.delete_stock), name="delete_stock"),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('reducir_stock/', login_required(sViews.reducir_stock), name='reducir_stock')
]

#if settings.DEBUG:
#    from django.conf.urls.static import static
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import register


urlpatterns = [
    path('register/', register, name='register'),
]

stockList/urls.py
from django.urls import path
from . import views

app_name = 'stockList'

urlpatterns = [
    path('reporte_excel/', views.ReporteExcel.as_view(), name='reporte_excel'),
]

stockList/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.

tiposDeProducto = (("Original", "Original"), ("Marca alterna", "Marca alterna"))

class Tables(models.Model):
    codProd = models.IntegerField(default=0, blank=False, null=False)
    nomProd = models.CharField(max_length=20, blank=False, null=False)
    calificacion = models.TextField(max_length=20, blank=False, null=False, choices=tiposDeProducto, verbose_name="Calificación")
    tipoProd = models.TextField(max_length=13, blank=False, null=False)
    stock = models.IntegerField(default=0, blank=False, null=False)

    class Meta:
        verbose_name = "Table"
        verbose_name_plural = "Tables"
    
    def __str__(self):
        return self.nomProd

    def clean(self):
        #valida que solo Stock 
        if self.stock < 0:
            raise ValidationError("El stock no puede ser menor que 0.")
        #valida que solo sean numeros con isdigit
        if not str(self.codProd).isdigit:
            raise ValidationError("El código del producto debe contener solo números.")

    def save(self, *args, **kwargs):
        self.clean()  
        super().save(*args, **kwargs)

stockList/forms.py
from django import forms
from .models import Tables
from django.forms import CharField, IntegerField

class TablesCreateForm(forms.ModelForm):
    codProd=IntegerField( label="Codigo del producto " ,required=True, widget=forms.NumberInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))
    nomProd=CharField( label="Nombre del producto",max_length=20, required=True, widget=forms.TextInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))
    tipoProd=CharField(label="Tipo del producto", max_length=13, required=True, widget=forms.TextInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))
    stock=IntegerField(label="Stock del producto", required=True, widget=forms.NumberInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))



    class Meta:
        model=Tables
        fields=['codProd', 'nomProd', 'calificacion', 'tipoProd', 'stock']
    def clean_codProd(self):
        codProd = self.cleaned_data['codProd']

        if Tables.objects.filter(codProd=codProd).exists():
            raise forms.ValidationError('Código de producto ya existente')
        return codProd



class TablesUpdateForm(forms.ModelForm):
    nomProd=CharField( label="Nombre del producto",max_length=20, required=True, widget=forms.TextInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))
    tipoProd=CharField(label="Tipo del producto", max_length=13, required=True, widget=forms.TextInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))
    stock=IntegerField(label="Stock del producto", required=True, widget=forms.NumberInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))
    
    class Meta:
        model=Tables
        fields=['nomProd', 'calificacion', 'tipoProd', 'stock']

class TablesSearchForm(forms.ModelForm):
    codProd=IntegerField( label="Codigo" ,required=False, widget=forms.NumberInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))
    nomProd=CharField( label="Nombre",max_length=20, required=False, widget=forms.TextInput(attrs={'class':'form-control form-control-user bg-light small', 'aria-describedby':'basic-addon2'}))

    class Meta:
        model = Tables
        fields = ['codProd', 'nomProd']

stockList/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Tables
from django.core.paginator import Paginator
from .forms import *
from django.views.generic import TemplateView
from openpyxl import Workbook
from django.http import HttpResponse
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter
from django.contrib import messages



# Create your views here.


def tables(request):
    tablesEntries=Tables.objects.all().order_by('id')
    form=TablesSearchForm(request.POST or None)
    paginator = Paginator(tablesEntries, 5) #paginador, dividido por 5 entradas en cada pagina
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "form": form,
        "everyEntry": tablesEntries,
        "page_obj": page_obj,
        } #contexto para la página, para definirlo de una sola forma
    if request.method == 'POST': #Si hubo un método post dentro del html
        page_obj = Tables.objects.filter(codProd__icontains=form['codProd'].value(), #filtra las tablas por estos valores
                                        nomProd__icontains=form['nomProd'].value()
                                        )
        context = {
        "form": form,
        "everyEntry": tablesEntries,
        "page_obj": page_obj,
        }
    return render(request, "stockList/tables.html", context)

def add_stock(request):
    form = TablesCreateForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'Guardado exitosamente')
        return redirect('/adding_stock/')
    context = {
		"form": form,
		"title": "Add Item",
	}
    return render(request, "stockList/add_stock.html", context)

def update_stock(request, pk):
    queryset = Tables.objects.get(id=pk)
    form = TablesUpdateForm(instance=queryset)
    if request.method == 'POST':
        form = TablesUpdateForm(request.POST, instance=queryset)
        if form.is_valid():
            form.save()
            messages.success(request, 'Actualizado exitosamente')
            return redirect('/tables/')
    context = {
		'form':form
    }
    return render(request, 'stockList/add_stock.html', context)

def delete_stock(request, pk):
    queryset = Tables.objects.get(id=pk)
    if request.method == 'POST':
        queryset.delete()
        messages.success(request, 'Eliminado exitosamente')
        return redirect('/tables/')
    return render(request, 'stockList/delete_stock.html')

def reducir_stock(request):
    mensaje = ""
    if request.method == 'POST':
        codProd = request.POST.get('codProd')
        cantidad = int(request.POST.get('cantidad'))

        # Buscar todos los productos por su código
        productos = Tables.objects.filter(codProd=codProd)

        if productos.exists():
            for producto in productos:
                if cantidad > 0 and producto.stock >= cantidad:
                    # Reducir el stock
                    producto.stock -= cantidad
                    producto.save()
                    mensaje = f'Stock del producto {producto.nomProd} reducido en {cantidad}. Stock actual: {producto.stock}.'
                else:
                    mensaje = 'Cantidad no válida o stock insuficiente.'
        else:
            mensaje = 'Producto no encontrado.'

    context = {
        'mensaje': mensaje
    }

    return render(request, 'stockList/reducir_stock.html', context)



class ReporteExcel(TemplateView):
    def get(self, request, *args, **kwargs):
        productos = Tables.objects.all()
        wb = Workbook()
        ws = wb.active
        
        
        ws['B1'] = 'Productos de Bodega'
        ws.merge_cells('B1:E1')
        ws['B1'].font = Font(size=14, bold=True)
        ws['B1'].alignment = Alignment(horizontal='center')
        
        
        headers = ['Código Producto', 'Nombre Producto', 'Calificación', 'Tipo de Producto', 'Stock']
        col_idx = 2
        for header in headers:
            cell = ws.cell(row=3, column=col_idx)
            cell.value = header
            cell.font = Font(bold=True)
            cell.alignment = Alignment(horizontal='center')
            cell.fill = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")
            col_idx += 1
        
      
        cont = 5
        for producto in productos:
            ws.cell(row=cont, column=2).value = producto.codProd
            ws.cell(row=cont, column=3).value = producto.nomProd
            ws.cell(row=cont, column=4).value = producto.calificacion
            ws.cell(row=cont, column=5).value = producto.tipoProd
            ws.cell(row=cont, column=6).value = producto.stock
            cont += 1
        
        
        for col in ws.iter_cols(min_col=2, max_col=6):
            max_length = 0
            column_letter = get_column_letter(col[0].column)
            for cell in col:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
                except:
                    pass
            adjusted_width = (max_length + 2)
            ws.column_dimensions[column_letter].width = adjusted_width
        
        nombre_archivo = "Productos_Bodega.xlsx"
        response = HttpResponse(content_type='application/ms-excel')
        content = "attachment; filename={0}".format(nombre_archivo)
        response['Content-Disposition'] = content
        wb.save(response)
        return response

stockList/templates/stockList/add_stock.html
{% extends "core/base.html" %}
{% load static %}

{% block styles %}
<link href="{% static 'core/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'core/css/sb-admin-2.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Añadir producto</h1>
                    {% if messages %}
                    <ul class="messages">
                           {% for message in messages %}
                                 <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                           {% endfor %}
                   </ul>
                    {% endif %}
                    <div>
                    <form method='POST' action='' class="user form-floating">{% csrf_token %}
                        <div class="form-group">
                            {{form.as_p}}
                        </div>
                        
                        <button class="btn btn-primary" type="submit" value='Save'>Guardar</button>
                    </form>
                    <hr>


                </div>
            </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
{% endblock %}

{% block js %}
<script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'core/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'core/js/sb-admin-2.min.js' %}"></script>
{% endblock %}

stockList/templates/stockList/delete_stock.html
{% extends "core/base.html" %}
{% load static %}

{% block styles %}
<link href="{% static 'core/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'core/css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% endblock  %}

    {% block content %}
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->

                    <form method="post" action="">
                        {% csrf_token %}
                          <h1>¿Seguro de que quiere borrar este producto?</h1><br>
                          <input class="btn btn-danger" type="submit" value="Si" />
                          <a href="/tables/"><div class="btn btn-primary">Cancelar</div></a>
                     </form>


                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            {% endblock %}

{% block js %}
<script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'core/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'core/js/sb-admin-2.min.js' %}"></script>
{% endblock  %}

stockList/templates/stockList/reducir_stock.html
{% extends "core/base.html" %}
{% load static %}

{% block styles %}
<link href="{% static 'core/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'core/css/sb-admin-2.min.css' %}" rel="stylesheet">
{% endblock  %}

    {% block content %}
    <div class="container-fluid">
        <h1>Reducir Stock</h1>
        <form action="{% url 'reducir_stock' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="codProd" class="form-label">Código del Producto</label>
                <input type="number" id="codProd" name="codProd" class="form-control" required>
            </div>
            <div class="mb-3">
                <label for="cantidad" class="form-label">Cantidad a Reducir</label>
                <input type="number" id="cantidad" name="cantidad" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary" style="margin-left:30px;">Reducir Stock</button>
        </form>
        {% if mensaje %}
            <p>{{ mensaje }}</p>
        {% endif %}
        <a href="{% url 'index' %}" style="margin-left:36px;">Volver al inicio</a>
    </div>
    <hr>

    {% endblock %}

    {% block js %}
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
    <!-- Core plugin JavaScript-->
    <script src="{% static 'core/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    
    <!-- Custom scripts for all pages-->
    <script src="{% static 'core/js/sb-admin-2.min.js' %}"></script>
    {% endblock  %}

stockList/templates/stockList/tables.html
{% extends "core/base.html" %}
{% load static %}



{% block styles %}
<!-- Custom fonts for this template -->
<link href="{% static 'core/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!-- Custom styles for this template -->
<link href="{% static 'core/css/sb-admin-2.min.css' %}" rel="stylesheet">

<!-- Custom styles for this page -->
<link href="{% static 'core/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}





{% block content %}
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    {% if messages %}
                    <ul class="messages">
                           {% for message in messages %}
                                 <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                           {% endfor %}
                   </ul>
                    {% endif %}



                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Productos</h6>
                        </div>
                        <div>
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary">Buscar producto</h6>
                            
                            <form class="navbar-search" method="POST" action="">
                                {% csrf_token %}
                                    <div class="input-group">
                                        <div class="border-0" aria-label="Search" aria-describedby="basic-addon2" style="margin-left:10px; margin-right:10px">
                                        {{form.as_table}}
                                        
                                        </div>
                                        <div class="">
                                            <input class="btn btn-primary" type="submit" value="Buscar" style="margin-top:65px;">
                                        </input>
                                        </div>
                                       
                                    </div>
                                </div>
                            </form>
                        </div>
                        <hr>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Codigo de producto</th>
                                            <th>Nombre de producto</th>
                                            <th>Calificación</th>
                                            <th>Tipo de producto</th>
                                            <th>Stock</th>
                                            <th>Eliminar</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Codigo de producto</th>
                                            <th>Nombre de producto</th>
                                            <th>Calificación</th>
                                            <th>Tipo de producto</th>
                                            <th>Stock</th>
                                            <th>Eliminar</th>
                                        </tr>
                                    </tfoot>
                                    {% for product in page_obj%}
                                    <tbody>
                                        <tr>
                                            <td>{{product.codProd}}</td>
                                            <td><a href="{% url 'update_stock' product.id %}">{{product.nomProd}}</a></td>
                                            <td>{{product.calificacion}}</td>
                                            <td>{{product.tipoProd}}</td>
                                            <td>{{product.stock}}</td>
                                            <td><a href="{% url 'delete_stock' product.id %}">Eliminar producto</a></td>

                                        </tr>
                                    </tbody>
                                    {% endfor %}
                                </table>
                                {% if perfil_usuario.ocupacion == "jefe de Inventario" %}
                                <a href="{% url 'stockList:reporte_excel' %}" class="btn btn-success">Excel</a>
                                {% endif %}
                                

                                <div class="btn-group paginator-style Bbutton" role="group" aria-label="Basic outlined example">

                                    {% if page_obj.has_previous %}
                                    <a href="?page={{ page_obj.previous_page_number }}">
                                        <button  type="button" class="btn btn-outline-primary paginator-buttons">Anterior</button>
                                    </a>
                                        
                                    {% endif %}
                            
                                    <span class="current pageNumerator">
                                        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                                    </span>

                                    {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">
                                        <button type="button" class="btn btn-outline-primary paginator-buttons">Siguiente</button>
                                    </a>

                                    
                                    {% endif %}
                                    
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

{% endblock %}
{% block js %}
<!-- Bootstrap core JavaScript-->
<script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'core/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'core/js/sb-admin-2.min.js' %}"></script>


<!-- Page level custom scripts -->
<script src="{% static 'core/js/demo/datatables-demo.js' %}"></script>

<!-- Bootstrap code for buttons -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}